export default [
  {
    vote_average: 8.1,
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    release_date: '2021-09-15',
    adult: false,
    backdrop_path: '/x6E7DS5ZcMoCITjkO0RiLLQ9Nb0.jpg',
    vote_count: 1980,
    genre_ids: [28, 12, 18, 878],
    id: 438631,
    original_language: 'en',
    original_title: 'Dune',
    poster_path: '/8hoD5BQuUV9dDecAbiyVIxLjzZ9.jpg',
    title: 'Dune',
    video: false,
    popularity: 3892.202,
    media_type: 'movie',
  },
  {
    id: 580489,
    overview:
      'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
    release_date: '2021-09-30',
    adult: false,
    original_language: 'en',
    backdrop_path: '/lNyLSOKMMeUPr1RsL4KcRuIXwHt.jpg',
    poster_path: '/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
    genre_ids: [878, 28],
    video: false,
    vote_average: 7,
    title: 'Venom: Let There Be Carnage',
    vote_count: 990,
    original_title: 'Venom: Let There Be Carnage',
    popularity: 7158.512,
    media_type: 'movie',
  },
  {
    genre_ids: [27, 53],
    original_language: 'en',
    original_title: 'Halloween Kills',
    poster_path: '/qmJGd5IfURq8iPQ9KF3les47vFS.jpg',
    id: 610253,
    vote_average: 7.5,
    vote_count: 591,
    overview:
      "Minutes after Laurie Strode, her daughter Karen and granddaughter Allyson left masked monster Michael Myers caged and burning in Laurie's basement, Laurie is rushed to the hospital with life-threatening injuries, believing she finally killed her lifelong tormentor. But when Michael manages to free himself from Laurie's trap, his ritual bloodbath resumes. As Laurie fights her pain and prepares to defend herself against him, she inspires all of Haddonfield to rise up against their unstoppable monster. The Strode women join a group of other survivors of Michael's first rampage who decide to take matters into their own hands, forming a vigilante mob that sets out to hunt Michael down, once and for all.",
    release_date: '2021-10-14',
    video: false,
    title: 'Halloween Kills',
    adult: false,
    backdrop_path: '/2cdrhlf3hvvueGyQDx0u8jpWvQR.jpg',
    popularity: 3654.224,
    media_type: 'movie',
  },
  {
    id: 550988,
    overview:
      'A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.',
    release_date: '2021-08-11',
    adult: false,
    original_language: 'en',
    backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
    poster_path: '/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg',
    genre_ids: [35, 28, 12, 878],
    video: false,
    vote_average: 7.8,
    title: 'Free Guy',
    vote_count: 3009,
    original_title: 'Free Guy',
    popularity: 3300.333,
    media_type: 'movie',
  },
  {
    id: 744275,
    adult: false,
    backdrop_path: '/qD45xHA35HdJDGOaA1AgDwiWEgO.jpg',
    genre_ids: [10749, 18],
    original_language: 'en',
    original_title: 'After We Fell',
    poster_path: '/3WfvjNWr5k1Zzww81b3GWc8KQhb.jpg',
    vote_count: 404,
    video: false,
    vote_average: 7.9,
    title: 'After We Fell',
    overview:
      "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
    release_date: '2021-09-01',
    popularity: 1274.877,
    media_type: 'movie',
  },
  {
    adult: false,
    backdrop_path: '/u5Fp9GBy9W8fqkuGfLBuuoJf57Z.jpg',
    genre_ids: [12, 28, 53],
    id: 370172,
    original_language: 'en',
    original_title: 'No Time to Die',
    poster_path: '/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg',
    video: false,
    title: 'No Time to Die',
    vote_count: 884,
    overview:
      'Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
    release_date: '2021-09-29',
    vote_average: 7.3,
    popularity: 466.822,
    media_type: 'movie',
  },
  {
    original_title: 'Night Teeth',
    poster_path: '/kVEUyxlHidvk5K8viOwMKtPNCNf.jpg',
    video: false,
    vote_average: 6.6,
    overview:
      'A college student moonlighting as a chauffeur picks up two mysterious women for a night of party-hopping across LA. But when he uncovers their bloodthirsty intentions - and their dangerous, shadowy underworld - he must fight to stay alive.',
    id: 669671,
    vote_count: 74,
    adult: false,
    backdrop_path: '/qvONzCnkwYXD47bbFuoZ0aKjtdp.jpg',
    title: 'Night Teeth',
    genre_ids: [27, 53, 28, 14],
    release_date: '2021-10-20',
    original_language: 'en',
    popularity: 179.116,
    media_type: 'movie',
  },
  {
    id: 385128,
    release_date: '2021-05-19',
    adult: false,
    backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
    vote_count: 4139,
    genre_ids: [28, 80, 53],
    vote_average: 7.4,
    original_language: 'en',
    original_title: 'F9',
    poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    video: false,
    title: 'F9',
    popularity: 883.467,
    media_type: 'movie',
  },
  {
    adult: false,
    backdrop_path: '/q4h2ZbhHKhnWvrrqzcjT778zlbn.jpg',
    genre_ids: [16, 878, 14, 28],
    id: 831405,
    original_language: 'en',
    original_title: 'Injustice',
    poster_path: '/lNRdCfVcjLs2LhO1Vb5rgnHV4JW.jpg',
    video: false,
    title: 'Injustice',
    vote_count: 237,
    overview:
      'When Lois Lane is killed, an unhinged Superman decides to take control of the Earth. Determined to stop him, Batman creates a team of freedom-fighting heroes. But when superheroes go to war, can the world survive?',
    release_date: '2021-10-09',
    vote_average: 8.1,
    popularity: 1282.961,
    media_type: 'movie',
  },
  {
    adult: false,
    backdrop_path: '/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg',
    genre_ids: [28, 12, 14],
    original_language: 'en',
    original_title: 'The Suicide Squad',
    poster_path: '/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg',
    vote_count: 4473,
    id: 436969,
    vote_average: 7.8,
    video: false,
    overview:
      'Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.',
    release_date: '2021-07-28',
    title: 'The Suicide Squad',
    popularity: 1014.343,
    media_type: 'movie',
  },
  {
    adult: false,
    backdrop_path: '/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg',
    genre_ids: [28, 12],
    original_language: 'en',
    original_title: 'Snake Eyes: G.I. Joe Origins',
    poster_path: '/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg',
    vote_count: 706,
    id: 568620,
    vote_average: 6.9,
    video: false,
    overview:
      "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
    release_date: '2021-07-22',
    title: 'Snake Eyes: G.I. Joe Origins',
    popularity: 1811.492,
    media_type: 'movie',
  },
  {
    genre_ids: [28, 53, 80],
    original_language: 'en',
    original_title: 'Copshop',
    poster_path: '/szArp3dQlVajpsqpyPFVAFHFsa3.jpg',
    id: 738652,
    vote_average: 6.3,
    vote_count: 50,
    overview:
      'On the run from a lethal assassin, a wily con artist devises a scheme to hide out inside a small-town police station. However, when the hit man turns up at the precinct, an unsuspecting rookie cop finds herself caught in the crosshairs.',
    release_date: '2021-09-09',
    video: false,
    title: 'Copshop',
    adult: false,
    backdrop_path: '/q8iOIJLvIcz5x38RrLudHQI5644.jpg',
    popularity: 74.884,
    media_type: 'movie',
  },
  {
    genre_ids: [16, 35, 10751],
    original_language: 'en',
    original_title: 'The Addams Family 2',
    poster_path: '/xYLBgw7dHyEqmcrSk2Sq3asuSq5.jpg',
    video: false,
    id: 639721,
    overview:
      'The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters.',
    release_date: '2021-10-01',
    vote_count: 368,
    vote_average: 7.6,
    adult: false,
    backdrop_path: '/kTOheVmqSBDIRGrQLv2SiSc89os.jpg',
    title: 'The Addams Family 2',
    popularity: 1857.53,
    media_type: 'movie',
  },
];
